In [2]:
import pandas as pd
import glob

In [10]:
file_paths = glob.glob('C:/Users/admin/Desktop/SelfCaseStudy/National AQI Project/*.xlsx')

In [11]:
dfs=[]
for files in file_paths:
    df=pd.read_excel(files)
    dfs.append(df)

In [15]:
len(dfs)
dfs[0].head()

,Date,00:00:00,01:00:00,02:00:00,03:00:00,04:00:00,05:00:00,06:00:00,07:00:00,08:00:00,...,14:00:00,15:00:00,16:00:00,17:00:00,18:00:00,19:00:00,20:00:00,21:00:00,22:00:00,23:00:00
0,1,102,94,96,93,92,98,101,98,97,...,83.0,82.0,71,78,69,68,79,88,92,93
1,2,90,86,83,118,132,91,91,96,97,...,77.0,82.0,84,86,83,75,77,83,79,74
2,3,82,80,77,76,78,72,72,71,70,...,76.0,79.0,83,81,85,88,93,90,83,84
3,4,87,81,77,75,71,72,71,69,71,...,76.0,77.0,79,76,80,90,96,90,84,82
4,5,79,73,71,73,75,72,70,73,76,...,104.0,112.0,108,116,108,122,103,90,82,80

In [16]:
combined_df = pd.concat(dfs, ignore_index=True)
combined_df.head()  # view first few rows

,Date,00:00:00,01:00:00,02:00:00,03:00:00,04:00:00,05:00:00,06:00:00,07:00:00,08:00:00,...,14:00:00,15:00:00,16:00:00,17:00:00,18:00:00,19:00:00,20:00:00,21:00:00,22:00:00,23:00:00
0,1,102,94.0,96.0,93,92.0,98.0,101.0,98,97.0,...,83.0,82.0,71,78.0,69.0,68.0,79.0,88,92.0,93.0
1,2,90,86.0,83.0,118,132.0,91.0,91.0,96,97.0,...,77.0,82.0,84,86.0,83.0,75.0,77.0,83,79.0,74.0
2,3,82,80.0,77.0,76,78.0,72.0,72.0,71,70.0,...,76.0,79.0,83,81.0,85.0,88.0,93.0,90,83.0,84.0
3,4,87,81.0,77.0,75,71.0,72.0,71.0,69,71.0,...,76.0,77.0,79,76.0,80.0,90.0,96.0,90,84.0,82.0
4,5,79,73.0,71.0,73,75.0,72.0,70.0,73,76.0,...,104.0,112.0,108,116.0,108.0,122.0,103.0,90,82.0,80.0

In [17]:
combined_df.info()
combined_df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 365 entries, 0 to 364
Data columns (total 25 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Date      365 non-null    int64
 1   00:00:00  365 non-null    int64
 2   01:00:00  364 non-null    float64
 3   02:00:00  364 non-null    float64
 4   03:00:00  365 non-null    int64
 5   04:00:00  364 non-null    float64
 6   05:00:00  364 non-null    float64
 7   06:00:00  364 non-null    float64
 8   07:00:00  365 non-null    int64
 9   08:00:00  364 non-null    float64
 10  09:00:00  365 non-null    int64
 11  10:00:00  364 non-null    float64
 12  11:00:00  365 non-null    int64
 13  12:00:00  365 non-null    int64
 14  13:00:00  364 non-null    float64
 15  14:00:00  363 non-null    float64
 16  15:00:00  362 non-null    float64
 17  16:00:00  365 non-null    int64
 18  17:00:00  364 non-null    float64
 19  18:00:00  362 non-null    float64
 20  19:00:00  363 non-null    float64
 21  20:00:00  364 non-null    float64
 22  21:00:00  365 non-null    int64
 23  22:00:00  364 non-null    float64
 24  23:00:00  364 non-null    float64
dtypes: float64(16), int64(9)
memory usage: 71.4 KB

,Date,00:00:00,01:00:00,02:00:00,03:00:00,04:00:00,05:00:00,06:00:00,07:00:00,08:00:00,...,14:00:00,15:00:00,16:00:00,17:00:00,18:00:00,19:00:00,20:00:00,21:00:00,22:00:00,23:00:00
count,365.000000,365.000000,364.000000,364.000000,365.000000,364.000000,364.000000,364.000000,365.00000,364.000000,...,363.000000,362.000000,365.000000,364.000000,362.000000,363.000000,364.000000,365.000000,364.000000,364.000000
mean,15.720548,91.183562,88.703297,87.065934,85.263014,83.769231,81.752747,81.799451,81.80000,83.590659,...,82.614325,81.955801,82.424658,83.046703,84.792818,87.421488,90.700549,93.446575,93.678571,92.969780
std,8.808321,25.802329,26.026367,25.475447,25.726731,25.693608,25.413807,25.522979,25.41266,27.033089,...,18.369294,17.865246,17.453012,16.602483,16.415777,17.429932,19.044703,21.742259,23.992733,25.822058
min,1.000000,44.000000,42.000000,40.000000,39.000000,37.000000,40.000000,41.000000,40.00000,40.000000,...,42.000000,47.000000,44.000000,43.000000,48.000000,53.000000,52.000000,49.000000,44.000000,44.000000
25%,8.000000,72.000000,69.000000,67.000000,64.000000,63.000000,61.000000,62.000000,61.00000,60.000000,...,69.000000,69.000000,70.000000,72.000000,73.000000,74.000000,77.000000,79.000000,77.000000,74.000000
50%,16.000000,90.000000,87.000000,86.000000,83.000000,80.000000,80.000000,78.000000,80.00000,80.500000,...,81.000000,81.000000,82.000000,83.000000,84.000000,88.000000,91.000000,94.000000,93.000000,92.000000
75%,23.000000,109.000000,106.250000,106.000000,101.000000,101.000000,97.000000,97.000000,97.00000,102.000000,...,95.000000,92.000000,94.000000,94.000000,96.000000,99.000000,103.000000,108.000000,110.000000,109.000000
max,31.000000,287.000000,256.000000,205.000000,187.000000,204.000000,195.000000,185.000000,170.00000,171.000000,...,150.000000,165.000000,143.000000,131.000000,141.000000,137.000000,166.000000,245.000000,273.000000,304.000000

In [23]:
import requests

url = 'aqicn.org/data-platform/api/H9067'
response = requests.get(url)
data = response.json()

df_api = pd.json_normalize(data['results'])

MissingSchema: Invalid URL 'aqicn.org/data-platform/api/H9067': No scheme supplied. Perhaps you meant https://aqicn.org/data-platform/api/H9067?